png("Model1_ED_scores.png")
plot(M1simEDstn, M1estEDstn, xlab = "Simulated ED scores", ylab = "Reconstructed ED scores", xlim = range(0, 0.04), ylim = range(0, 0.04), col = rgb(0, 0, 0, .2))
dev.off()
png("Model2_ED_scores.png")
plot(M2simEDstn, M2estEDstn, xlab = "Simulated ED scores", ylab = "Reconstructed ED scores", xlim = range(0, 0.04), ylim = range(0, 0.04), col = rgb(0, 0, 0, .2))
dev.off()
png("Model3_ED_scores.png")
plot(M3simEDstn, M3estEDstn, xlab = "Simulated ED scores", ylab = "Reconstructed ED scores", xlim = range(0, 0.04), ylim = range(0, 0.04), col = rgb(0, 0, 0, .2))
dev.off()
png("Model4_ED_scores.png")
plot(M4simEDstn, M4estEDstn, xlab = "Simulated ED scores", ylab = "Reconstructed ED scores", xlim = range(0, 0.04), ylim = range(0, 0.04), col = rgb(0, 0, 0, .2))
dev.off()
png("Model1_ED_scores_ranked.png")
plot(M1RankSimEDstn, M1RankEstEDstn, xlab = "Ranked simulated ED scores", ylab = "Ranked reconstructed ED scores", xlim = range(0, 210), ylim = range(0, 210), col = rgb(0, 0, 0, .2))
dev.off()
png("Model2_ED_scores_ranked.png")
plot(M2RankSimEDstn, M2RankEstEDstn, xlab = "Ranked simulated ED scores", ylab = "Ranked reconstructed ED scores", xlim = range(0, 210), ylim = range(0, 210), col = rgb(0, 0, 0, .2))
dev.off()
png("Model3_ED_scores_ranked.png")
plot(M3RankSimEDstn, M3RankEstEDstn, xlab = "Ranked simulated ED scores", ylab = "Ranked reconstructed ED scores", xlim = range(0, 210), ylim = range(0, 210), col = rgb(0, 0, 0, .2))
dev.off()
png("Model4_ED_scores_ranked.png")
plot(M4RankSimEDstn, M4RankEstEDstn, xlab = "Ranked simulated ED scores", ylab = "Ranked reconstructed ED scores", xlim = range(0, 210), ylim = range(0, 210), col = rgb(0, 0, 0, .2))
dev.off()